version: '3.3'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/db/:/data/db
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

  filmtracker:
    build: .
    restart: always
    ports:
      - 5555:5555
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
    env_file:
      - .env

  filmtracker-web:
    build: database/dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - filmtracker
