basePath: '{{.BasePath}}'
host: localhost:5555
info:
  contact: {}
  description: DITS test FilmTracker project.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: FilmTracker API
  version: "1.0"
paths:
  /users/auth/signout/:
    get:
      consumes:
      - application/json
      description: Sign Out from server, delete cookies
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":"Sign Out"}'
          schema:
            type: string
        "406":
          description: '{"error":"http: named cookie not present"}'
          schema:
            type: string
      summary: Sign Out
      tags:
      - users
securityDefinitions:
  Refresh:
    in: cookies
    name: Refresh
    type: apiKey
  Token:
    in: cookies
    name: Token
    type: apiKey
swagger: "2.0"
